github: [Goba]
custom: ["https://www.buymeacoffee.com/goba"]
tidelift: # 替换为实际的Tidelift项目ID
community_bridge: # 替换为实际的CommunityBridge项目ID
issuehunt: # 替换为实际的IssueHunt项目ID
otechie: # 替换为实际的Otechie项目ID
liberapay: # 替换为实际的Liberapay项目ID
patreon: # 替换为实际的Patreon项目ID